import { PageTransition } from "@/components/PageTransition";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";

export default function ProvablyFair() {
  return (
    <PageTransition>
      <div className="min-h-screen bg-[#14151A] py-12 overflow-y-auto">
        <main className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-4xl mx-auto"
          >
            <h1 className="text-4xl md:text-5xl font-heading font-bold text-white mb-8">
              Provably Fair
            </h1>

            <div className="space-y-8">
              <section className="bg-[#1A1B21]/50 backdrop-blur-sm p-6 rounded-lg border border-[#2A2B31]">
                <h2 className="text-2xl font-heading text-white mb-4">
                  What is provable fairness?
                </h2>
                <p className="text-[#8A8B91] leading-relaxed">
                  Provable fairness is a method in online gaming that guarantees
                  every game outcome is determined by a truly random process,
                  free from manipulation by the operator or any other party.
                  This ensures that all players have equal odds of winning and
                  that the results are entirely random and unpredictable.
                </p>
              </section>

              <section className="bg-[#1A1B21]/50 backdrop-blur-sm p-6 rounded-lg border border-[#2A2B31]">
                <h2 className="text-2xl font-heading text-white mb-4">
                  How Does Goated Ensure Provably Fair Bets?
                </h2>
                <p className="text-[#8A8B91] mb-4">
                  At Goated, our provably fair system includes:
                </p>
                <ul className="text-[#8A8B91] space-y-2 list-disc pl-6">
                  <li>Game seed: A random value generated by our server</li>
                  <li>
                    Client Seed: A value created by your device at the start of
                    the game, in order to add the next layer of randomness
                  </li>
                  <li>
                    Cryptographic Nonce: A value that ensures it is impossible
                    for an identical set of seed to occur
                  </li>
                </ul>
                <p className="text-[#8A8B91] mt-4">
                  These three components are processed by our random number
                  generator to produce the game's outcome. This combination
                  ensures the results are random and cannot be manipulated.
                </p>
              </section>

              <section className="bg-[#1A1B21]/50 backdrop-blur-sm p-6 rounded-lg border border-[#2A2B31]">
                <h2 className="text-2xl font-heading text-white mb-4">
                  How can bets be verified as fair?
                </h2>
                <p className="text-[#8A8B91] mb-4">
                  To verify that a bet is fair, players can check the
                  server-side seed, client-side seed, and cryptographic nonce
                  via the verify page{" "}
                  <a
                    href="https://www.goated.com/fairness"
                    className="text-[#D7FF00] hover:text-[#D7FF00]/80 inline-flex items-center gap-1"
                  >
                    here
                    <ArrowRight className="h-4 w-4" />
                  </a>
                </p>
              </section>
            </div>
          </motion.div>
        </main>
      </div>
    </PageTransition>
  );
}
